baseurl = "https://deadfate.netlify.com/"
languageCode = "en-us"
title = "hohoho"
theme = "hugo-xmin"
googleAnalytics = "UA-156464110-1"
disqusShortname = "deadfate"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/Tags/"
    weight = 4
[[menu.main]]
    name = "todo"
    url = "/todo/"
    weight = 5
[params]
    description = "A website built through Hugo and blogdown."
    
    footer = "&copy; [本站採用CC4.0授權](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh_TW) | [plurk](https://www.plurk.com/deadfate_) | [Github](https://github.com/deadfate-sky/blog) | [Twitter](https://twitter.com/_deadfate)"
    
    highlightjsVersion = "9.15.10"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r"]
    highlightjsTheme = "github"
    